### ISSUE TITLE
Unable to create DMG

### ISSUE THREAD

**Issue by choonchernlim** [javafx-maven-plugin/javafx-maven-plugin#144]
I'm having difficulty creating a DMG file using this plugin on Mac (Yosemite). It creates both PKG and APP fine, but errors out when trying to create DMG.

Here's my simple config:-

```xml
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.1.3</version>
    <configuration>
        <mainClass>project.testJavaFx.FXMLExample</mainClass>
        <vendor>My project</vendor>
        <verbose>true</verbose>
    </configuration>
</plugin>
```

Somewhere along the printed log, I see this:-

```
Preparing dmg setup: /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler4827028321152347760/macosx/testJavafx-1.0.0-dmg-setup.scpt
  Using default package resource [DMG setup script]  (add package/macosx/testJavafx-1.0.0-dmg-setup.scpt to the class path to customize)
 Creating DMG file: /Users/limc/Documents/development/workspace/intellij/test-javafx/target/jfx/native/testJavafx-1.0.0-1.0.dmg
Running [/usr/bin/hdiutil, create, -quiet, -srcfolder, /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler4827028321152347760/images/image-4115177474692270843, -volname, testJavafx-1.0.0, -ov, /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler4827028321152347760/images/testJavafx-1.0.0-tmp.dmg, -format, UDRW]
java.io.IOException: Exec failed with code 1 command [[/usr/bin/hdiutil, create, -quiet, -srcfolder, /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler4827028321152347760/images/image-4115177474692270843, -volname, testJavafx-1.0.0, -ov, /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler4827028321152347760/images/testJavafx-1.0.0-tmp.dmg, -format, UDRW] in unspecified directory
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:165)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:138)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:132)
	at com.oracle.tools.packager.mac.MacDmgBundler.buildDMG(MacDmgBundler.java:326)
	at com.oracle.tools.packager.mac.MacDmgBundler.bundle(MacDmgBundler.java:85)
	at com.oracle.tools.packager.mac.MacDmgBundler.execute(MacDmgBundler.java:522)
	at com.zenjava.javafx.maven.plugin.NativeMojo.execute(NativeMojo.java:342)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
  Config files are saved to /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler4827028321152347760/macosx. Use them to customize package.
```

When I take that array command, strip out the commas and run them directly on Terminal, it creates the DMG just fine.

Can you kindly point out what I'm doing wrong here? 

Great plugin, by the way.

Thank you.

P/S: I'm using Java 8.

**Comment by FibreFoX** [comment]
Hm, nothing so far I can fix, it's inside javapackager itself:
https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/mac/MacDmgBundler.java#L326

Can you try to call `mvn jfx:native` on terminal, and not via your IntelliJ-IDE?

**Comment by choonchernlim** [comment]
I'm getting the same result by running from Terminal.... here's the full log:-

```
➜  test-javafx git:(master) java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
➜  test-javafx git:(master) javac -version
javac 1.8.0_51
➜  test-javafx git:(master) mvn clean jfx:native
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building test-javafx 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ test-javafx ---
[INFO] Deleting /Users/limc/Documents/development/workspace/intellij/test-javafx/target
[INFO]
[INFO] >>> javafx-maven-plugin:8.1.3:native (default-cli) > :jar @ test-javafx >>>
[INFO]
[INFO] >>> javafx-maven-plugin:8.1.3:jar (jar) > [jfxjar]package @ test-javafx >>>
[WARNING] The POM for com.google.guava:guava:jar:16.0.1 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test-javafx ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 9 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ test-javafx ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 12 source files to /Users/limc/Documents/development/workspace/intellij/test-javafx/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ test-javafx ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/limc/Documents/development/workspace/intellij/test-javafx/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ test-javafx ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ test-javafx ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ test-javafx ---
[INFO] Building jar: /Users/limc/Documents/development/workspace/intellij/test-javafx/target/test-javafx-1.0.0.jar
[INFO]
[INFO] <<< javafx-maven-plugin:8.1.3:jar (jar) < [jfxjar]package @ test-javafx <<<
[INFO]
[INFO] --- javafx-maven-plugin:8.1.3:jar (jar) @ test-javafx ---
[INFO] Building JavaFX JAR for application
[INFO] Adding 'deploy' directory to Mojo classpath: /Users/limc/Documents/development/workspace/intellij/test-javafx/src/main/deploy
[INFO]
[INFO] <<< javafx-maven-plugin:8.1.3:native (default-cli) < :jar @ test-javafx <<<
[INFO]
[INFO] --- javafx-maven-plugin:8.1.3:native (default-cli) @ test-javafx ---
[INFO] Building Native Installers
[INFO] Add /Users/limc/Documents/development/workspace/intellij/test-javafx/target/jfx/app/lib/aopalliance-1.0.jar file to application resources.
[INFO] Add /Users/limc/Documents/development/workspace/intellij/test-javafx/target/jfx/app/lib/guava-18.0.jar file to application resources.
[INFO] Add /Users/limc/Documents/development/workspace/intellij/test-javafx/target/jfx/app/lib/guice-4.0.jar file to application resources.
[INFO] Add /Users/limc/Documents/development/workspace/intellij/test-javafx/target/jfx/app/lib/javax.inject-1.jar file to application resources.
[INFO] Add /Users/limc/Documents/development/workspace/intellij/test-javafx/target/jfx/app/lib/log4j-1.2.17.jar file to application resources.
[INFO] Add /Users/limc/Documents/development/workspace/intellij/test-javafx/target/jfx/app/lib/slf4j-api-1.7.7.jar file to application resources.
[INFO] Add /Users/limc/Documents/development/workspace/intellij/test-javafx/target/jfx/app/lib/slf4j-log4j12-1.7.7.jar file to application resources.
[INFO] Add /Users/limc/Documents/development/workspace/intellij/test-javafx/target/jfx/app/test-javafx-1.0.0-jfx.jar file to application resources.
Preparing Info.plist: /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/macosx/Info.plist
  Using default package resource [Bundle config file]  (add package/macosx/Info.plist to the class path to customize)
  Using custom package resource [icon]  (loaded from package/macosx/test-javafx.icns)
Creating app bundle: /Users/limc/Documents/development/workspace/intellij/test-javafx/target/jfx/native/test-javafx.app
Running [security, find-certificate, -c, Developer ID Application: , -a]
Did not find a key matching 'Developer ID Application: '
  Config files are saved to /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/macosx. Use them to customize package.
Building DMG package for test-javafx
Preparing Info.plist: /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/macosx/Info.plist
  Using default package resource [Bundle config file]  (add package/macosx/Info.plist to the class path to customize)
  Using custom package resource [icon]  (loaded from package/macosx/test-javafx.icns)
Running [security, find-certificate, -c, Developer ID Application: , -a]
Did not find a key matching 'Developer ID Application: '
  Config files are saved to /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/macosx. Use them to customize package.
  Using default package resource [dmg background]  (add package/macosx/test-javafx-background.png to the class path to customize)
  Using default package resource [volume icon]  (add package/macosx/test-javafx-volume.icns to the class path to customize)
Using default package resource [script to run after application image is populated]  (add package/macosx/test-javafx-post-image.sh to the class path to customize)
Preparing dmg setup: /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/macosx/test-javafx-dmg-setup.scpt
  Using default package resource [DMG setup script]  (add package/macosx/test-javafx-dmg-setup.scpt to the class path to customize)
 Creating DMG file: /Users/limc/Documents/development/workspace/intellij/test-javafx/target/jfx/native/test-javafx-1.0.dmg
Running [/usr/bin/hdiutil, create, -quiet, -srcfolder, /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/images/image-8478971006993104783, -volname, test-javafx, -ov, /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/images/test-javafx-tmp.dmg, -format, UDRW]
java.io.IOException: Exec failed with code 1 command [[/usr/bin/hdiutil, create, -quiet, -srcfolder, /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/images/image-8478971006993104783, -volname, test-javafx, -ov, /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/images/test-javafx-tmp.dmg, -format, UDRW] in unspecified directory
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:165)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:138)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:132)
	at com.oracle.tools.packager.mac.MacDmgBundler.buildDMG(MacDmgBundler.java:326)
	at com.oracle.tools.packager.mac.MacDmgBundler.bundle(MacDmgBundler.java:85)
	at com.oracle.tools.packager.mac.MacDmgBundler.execute(MacDmgBundler.java:522)
	at com.zenjava.javafx.maven.plugin.NativeMojo.execute(NativeMojo.java:342)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
  Config files are saved to /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/macosx. Use them to customize package.
Building PKG package for test-javafx
Preparing Info.plist: /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/macosx/Info.plist
  Using default package resource [Bundle config file]  (add package/macosx/Info.plist to the class path to customize)
  Using custom package resource [icon]  (loaded from package/macosx/test-javafx.icns)
Running [security, find-certificate, -c, Developer ID Application: , -a]
Did not find a key matching 'Developer ID Application: '
  Config files are saved to /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/macosx. Use them to customize package.
  Using default package resource [pkg background image]  (add package/macosx/test-javafx-background.png to the class path to customize)
Preparing distribution.dist: /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/macosx/distribution.dist
Using default package resource [script to run after application image is populated]  (add package/macosx/test-javafx-post-image.sh to the class path to customize)
Running [pkgbuild, --component, /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/images/image-8478971006993104783/test-javafx.app, --install-location, /Applications, /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/packages/test-javafx-app.pkg]
pkgbuild: Adding component at /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/images/image-8478971006993104783/test-javafx.app
pkgbuild: Wrote package to /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/packages/test-javafx-app.pkg
Running [security, find-certificate, -c, Developer ID Installer: , -a]
Did not find a key matching 'Developer ID Installer: '
Running [productbuild, --resources, /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/macosx, --distribution, /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/macosx/distribution.dist, --package-path, /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/packages, /Users/limc/Documents/development/workspace/intellij/test-javafx/target/jfx/native/test-javafx-1.0.pkg]
productbuild: Wrote product to /Users/limc/Documents/development/workspace/intellij/test-javafx/target/jfx/native/test-javafx-1.0.pkg
  Config files are saved to /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/macosx. Use them to customize package.
Running [security, find-certificate, -c, 3rd Party Mac Developer Application: , -a]
Did not find a key matching '3rd Party Mac Developer Application: '
[INFO] Skipping Mac App Store Ready Bundler because of configuration error No Mac App Store App Signing Key
Advice to Fix: Install your app signing keys into your Mac Keychain using XCode.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.948 s
[INFO] Finished at: 2015-08-18T07:43:31-05:00
[INFO] Final Memory: 28M/1963M
[INFO] ------------------------------------------------------------------------
```

**Comment by FibreFoX** [comment]
I know, it's hard to reconstruct, but could you try to check this via ant?

This plugin just makes a wrapper around the ant-classes, so this might be a problem within javapackager itself, but there is no entry at the [javafx-JIRA](https://bugs.openjdk.java.net/issues/?jql=project%20%3D%20JDK%20AND%20component%20%3D%20deploy%20AND%20Subcomponent%20in%20%28packager%2C%20packager%2C%20packager%29%20AND%20text%20~%20%22dmg%22%20ORDER%20BY%20updated%20DESC)

Maybe it's a problem with local file-permissions? (don't have access to any mac-system)

**Comment by choonchernlim** [comment]
If I invoke this command directly from Terminal, it works just fine and the DMG gets created:-

```
/usr/bin/hdiutil create -quiet -srcfolder /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/images/image-8478971006993104783 -volname test-javafx -ov /var/folders/5j/s7tv9vqd6_z49346j8vkvn1cp74zbd/T/fxbundler5924214286744831651/images/test-javafx-tmp.dmg -format UDRW
```

**Comment by FibreFoX** [comment]
@choonchernlim Hi, have you been able to check, if with a current JDK this works again?

**Comment by FibreFoX** [comment]
@choonchernlim do you still have this problem?

**Comment by choonchernlim** [comment]
It's working for me now... Not sure why. Thank you.
