### ISSUE TITLE
Cannot build Mac Appstore PKG with Custom Entitlements File

### ISSUE THREAD

**Issue by sselvia** [javafx-maven-plugin/javafx-maven-plugin#145]
If you use a custom entitlements file in my package/macosx/<App Name>.entitlements the app store pkg build has the following exception.  I tried just the <App Name>.entitlements and the inherit version as well at the same time with the same results.

cd /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro; JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home "/Applications/NetBeans/NetBeans Dev 201506210001.app/Contents/Resources/NetBeans/java/maven/bin/mvn" clean jfx:native
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building Examine-IT-Pro 2.0.0
------------------------------------------------------------------------

--- maven-clean-plugin:2.4.1:clean (default-clean) @ Examine-IT-Pro ---
Deleting /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target

>>> javafx-maven-plugin:8.1.4-SNAPSHOT:native (default-cli) @ Examine-IT-Pro >>>

>>> javafx-maven-plugin:8.1.4-SNAPSHOT:jar (jar) @ Examine-IT-Pro >>>

--- maven-resources-plugin:2.5:resources (default-resources) @ Examine-IT-Pro ---
[debug] execute contextualize
Using 'UTF-8' encoding to copy filtered resources.
Copying 3 resources

--- maven-compiler-plugin:2.3.2:compile (default-compile) @ Examine-IT-Pro ---
Compiling 1 source file to /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/classes

--- maven-resources-plugin:2.5:testResources (default-testResources) @ Examine-IT-Pro ---
[debug] execute contextualize
Using 'UTF-8' encoding to copy filtered resources.
skip non existing resourceDirectory /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/src/test/resources

--- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ Examine-IT-Pro ---
Nothing to compile - all classes are up to date

--- maven-surefire-plugin:2.10:test (default-test) @ Examine-IT-Pro ---
No tests to run.
Surefire report directory: /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

--- maven-jar-plugin:2.3.2:jar (default-jar) @ Examine-IT-Pro ---
Building jar: /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/Examine-IT-Pro.jar

<<< javafx-maven-plugin:8.1.4-SNAPSHOT:jar (jar) @ Examine-IT-Pro <<<

--- javafx-maven-plugin:8.1.4-SNAPSHOT:jar (jar) @ Examine-IT-Pro ---
Building JavaFX JAR for application
Adding 'deploy' directory to Mojo classpath: /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/src/main/deploy

<<< javafx-maven-plugin:8.1.4-SNAPSHOT:native (default-cli) @ Examine-IT-Pro <<<

--- javafx-maven-plugin:8.1.4-SNAPSHOT:native (default-cli) @ Examine-IT-Pro ---
Building Native Installers
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/Examine-IT-Pro-jfx.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/bcprov-jdk15on-1.52.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/commons-codec-1.9.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/commons-lang-2.6.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/commons-lang3-3.4.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/commons-logging-1.1.1.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/controlsfx-8.20.9.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/Examine-IT-Desktop-2.0.0.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/Examine-IT-Framework-2.0.0.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/Examine-IT-Preloader-2.0.0.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/fontbox-1.8.9.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/itextpdf-5.5.6.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/jcl-over-slf4j-1.6.1.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/jempbox-1.8.9.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/log4j-1.2.16.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/openjfx-dialogs-1.0.3.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/pdfbox-1.8.9.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/poi-3.12.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/poi-ooxml-3.12.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/poi-ooxml-schemas-3.12.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/poi-scratchpad-3.12.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/slf4j-api-1.6.1.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/slf4j-log4j12-1.6.1.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/stax-api-1.0.1.jar file to application resources.
Add /Users/scottselvia/sourceCode.workspace/git/Examine-IT/Examine-IT-POM/Examine-IT-Pro/target/jfx/app/lib/xmlbeans-2.6.0.jar file to application resources.
Running [security, find-certificate, -c, 3rd Party Mac Developer Application: , -a]
Running [security, find-certificate, -c, 3rd Party Mac Developer Installer: , -a]
Building Mac App Store Bundle for Examine-IT-Pro
Preparing Info.plist: /var/folders/dj/0xr8h7gs44d00y56yczrhpch0000gn/T/fxbundler8009336151503383933/macosx/Info.plist
  Using default package resource [Bundle config file]  (add package/macosx/Info.plist to the class path to customize)
  Using custom package resource [icon]  (loaded from package/macosx/Examine-IT-Pro.icns)
  Config files are saved to /var/folders/dj/0xr8h7gs44d00y56yczrhpch0000gn/T/fxbundler8009336151503383933/macosx. Use them to customize package.
  Using custom package resource [Mac App Store Entitlements]  (loaded from package/macosx/Examine-IT-Pro.entitlements)
  Using default package resource [Mac App Store Inherit Entitlements]  (add package/macosx/Examine-IT-Pro_Inherit.entitlements to the class path to customize)
Running [codesign, -s, 3rd Party Mac Developer Application: Scott Selvia (TM2Q8MJ7ZY), --prefix, com.thundercloudresources.examineit.pro., -vvvv, /var/folders/dj/0xr8h7gs44d00y56yczrhpch0000gn/T/fxbundler8009336151503383933/images/image-6680320163501175992/Examine-IT-Pro.app/Contents/Info.plist]
/var/folders/dj/0xr8h7gs44d00y56yczrhpch0000gn/T/fxbundler8009336151503383933/images/image-6680320163501175992/Examine-IT-Pro.app/Contents/Info.plist: signed generic [com.thundercloudresources.examineit.pro.Info]
Running [codesign, -s, 3rd Party Mac Developer Application: Scott Selvia (TM2Q8MJ7ZY), --prefix, com.thundercloudresources.examineit.pro., -vvvv, --entitlements, /var/folders/dj/0xr8h7gs44d00y56yczrhpch0000gn/T/fxbundler8009336151503383933/macosx/Examine-IT-Pro.entitlements, /var/folders/dj/0xr8h7gs44d00y56yczrhpch0000gn/T/fxbundler8009336151503383933/images/image-6680320163501175992/Examine-IT-Pro.app/Contents/Java/Examine-IT-Pro-jfx.jar]
/var/folders/dj/0xr8h7gs44d00y56yczrhpch0000gn/T/fxbundler8009336151503383933/macosx/Examine-IT-Pro.entitlements: unrecognized blob type (accepting blindly)
/var/folders/dj/0xr8h7gs44d00y56yczrhpch0000gn/T/fxbundler8009336151503383933/macosx/Examine-IT-Pro.entitlements: invalid length in entitlement blob
App Store Ready Bundle failed : Exec failed with code 1 command [[codesign, -s, 3rd Party Mac Developer Application: Scott Selvia (TM2Q8MJ7ZY), --prefix, com.thundercloudresources.examineit.pro., -vvvv, --entitlements, /var/folders/dj/0xr8h7gs44d00y56yczrhpch0000gn/T/fxbundler8009336151503383933/macosx/Examine-IT-Pro.entitlements, /var/folders/dj/0xr8h7gs44d00y56yczrhpch0000gn/T/fxbundler8009336151503383933/images/image-6680320163501175992/Examine-IT-Pro.app/Contents/Java/Examine-IT-Pro-jfx.jar] in unspecified directory
java.io.IOException: Exec failed with code 1 command [[codesign, -s, 3rd Party Mac Developer Application: Scott Selvia (TM2Q8MJ7ZY), --prefix, com.thundercloudresources.examineit.pro., -vvvv, --entitlements, /var/folders/dj/0xr8h7gs44d00y56yczrhpch0000gn/T/fxbundler8009336151503383933/macosx/Examine-IT-Pro.entitlements, /var/folders/dj/0xr8h7gs44d00y56yczrhpch0000gn/T/fxbundler8009336151503383933/images/image-6680320163501175992/Examine-IT-Pro.app/Contents/Java/Examine-IT-Pro-jfx.jar] in unspecified directory
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:165)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:138)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:132)
	at com.oracle.tools.packager.mac.MacBaseInstallerBundler.lambda$signAppBundle$190(MacBaseInstallerBundler.java:277)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.oracle.tools.packager.mac.MacBaseInstallerBundler.signAppBundle(MacBaseInstallerBundler.java:246)
	at com.oracle.tools.packager.mac.MacAppStoreBundler.bundle(MacAppStoreBundler.java:132)
	at com.oracle.tools.packager.mac.MacAppStoreBundler.execute(MacAppStoreBundler.java:412)
	at com.zenjava.javafx.maven.plugin.NativeMojo.execute(NativeMojo.java:342)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
  Config files are saved to /var/folders/dj/0xr8h7gs44d00y56yczrhpch0000gn/T/fxbundler8009336151503383933/macosx. Use them to customize package.
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time: 7.358s
Finished at: Fri Aug 21 08:15:28 EDT 2015
Final Memory: 20M/255M
------------------------------------------------------------------------

**Comment by sselvia** [comment]
Close the Issue, the entitlements file has a <true/> element

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>com.apple.security.app-sandbox</key>
        <key>com.apple.security.files.user-selected.read-write</key>
        <true/>
    </dict>
</plist>
