### ISSUE TITLE
Unable to start application with jdk 8u66 on Windows XP

### ISSUE THREAD

**Issue by Rizen59** [javafx-maven-plugin/javafx-maven-plugin#175]
Hi all,

Since upgrading to JDK 8u66 from 8u51 we saw that native application cannot be launched on Windows XP anymore. The message is that the app is not a valid win32 application.
So for testing I packaged a simple app on jar file and launch it with both JDK 8u51 and 8u66.

Everythings works fine on 8u51 but here is the exception on 8u66 :
```java
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:221)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:205)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:337)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:217)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:337)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        ... 5 more
```

It's probably a bug from recent changes in JDK 8u60+ but I'd like to confirm this point here before add a new issue on the JDK database. Maybe you got more information.

**Comment by FibreFoX** [comment]
Hm ... so where do you think is the issue with javafx-maven-plugin?

**Comment by FibreFoX** [comment]
Just googled a bit, came up with this:
http://stackoverflow.com/questions/21185156/javafx-on-linux-is-showing-a-graphics-device-initialization-failed-for-es2-s#21203726 which points to the following existing bug-entry https://bugs.openjdk.java.net/browse/JDK-8120519 ... but its non-windows only.

Searching further i stumbled upon this: https://bugs.openjdk.java.net/browse/JDK-8092772

All in all, it might be a bug on your system (using local installed JRE instead of bundled one) or just being a bug inside the JDK.

Therefor this will be closed as invalid, as it has nothing todo with this maven-plugin. :smile: but you were right to double-check this here ;)
