### ISSUE TITLE
Signing issues building a Maven multi-module jfx app with custom controls

### ISSUE THREAD

**Issue by technosf** [javafx-maven-plugin/javafx-maven-plugin#181]
Building [Posterer](https://github.com/technosf/Posterer) with _jfx-m-p_ has been great as a monolithic app. 

I've just recently split it into a multi-module maven app, and moved some code out of the UI portion of the app into a separate custom control sub project. Now I'm hitting the issue below when building the app with _jfx-m-p_: 

```
Signing (BLOB) C:\opt\git\Posterer\App\target\jfx\web\lib\controls-0.0.1.jar
java.util.zip.ZipException: duplicate entry: META-INF/maven/com.github.technosf.posterer/controls/pom.xml
        at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
        at com.sun.javafx.tools.packager.JarSignature.signJarAsBLOB(JarSignature.java:491)
        at com.sun.javafx.tools.packager.PackagerLib.signAsBLOB(PackagerLib.java:483)
```
etc.

This issue can be created with the command:
`mvn -Dmaven.test.skip=true package`
in the tld of [Posterer](https://github.com/technosf/Posterer).

Would be grateful for some insight if this is a bug or if re-orging the mvn projects is in order (such as moving the custom controls out of the project hierarchy altogether).

Happy to see the Zen code base get worked on and come along!

Thank you for taking on _jfx-m-p_ and your diligence [FibreFox](https://github.com/FibreFoX)

**Comment by FibreFoX** [comment]
@technosf I've checked out the current that project and had no problem to bundle that project:

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Posterer
[INFO] Core
[INFO] Modules implementing functionality with specific libraries
[INFO] Posterer Controls
[INFO] Application
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Posterer 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Core 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\FibreFoX\Downloads\Posterer-master\Core\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ core ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ core ---
[INFO] Not copying test resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ core ---
[INFO] Not compiling test sources
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ core ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ core ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Modules implementing functionality with specific libraries 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ modules ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\FibreFoX\Downloads\Posterer-master\Modules\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ modules ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 18 source files to C:\Users\FibreFoX\Downloads\Posterer-master\Modules\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ modules ---
[INFO] Not copying test resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ modules ---
[INFO] Not compiling test sources
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ modules ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ modules ---
[INFO] Building jar: C:\Users\FibreFoX\Downloads\Posterer-master\Modules\target\modules-0.0.1.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Posterer Controls 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ controls ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ controls ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to C:\Users\FibreFoX\Downloads\Posterer-master\Controls\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ controls ---
[INFO] Not copying test resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ controls ---
[INFO] Not compiling test sources
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ controls ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ controls ---
[INFO] Building jar: C:\Users\FibreFoX\Downloads\Posterer-master\Controls\target\controls-0.0.1.jar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Application 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ app ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 12 source files to C:\Users\FibreFoX\Downloads\Posterer-master\App\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ app ---
[INFO] Not copying test resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ app ---
[INFO] Not compiling test sources
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ app ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ app ---
[INFO] Building jar: C:\Users\FibreFoX\Downloads\Posterer-master\App\target\app-0.0.1.jar
[INFO] 
[INFO] --- javafx-maven-plugin:8.2.0:build-jar (create-jfxjar) @ app ---
[INFO] Building JavaFX JAR for application
[INFO] Adding 'deploy' directory to Mojo classpath: C:\Users\FibreFoX\Downloads\Posterer-master\App/src/main/deploy
[INFO] 
[INFO] --- javafx-maven-plugin:8.2.0:build-web (create-web) @ app ---
[INFO] Building Web deployment bundles
[INFO] Adding 'deploy' directory to Mojo classpath: C:\Users\FibreFoX\Downloads\Posterer-master\App/src/main/deploy
No base JDK. Package will use system JRE.
No base JDK. Package will use system JRE.
[INFO] Permissions requested, signing JAR files for webstart bundle
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\app-0.0.1-jfx.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\app-0.0.1-jfx.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\aopalliance-1.0.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\aopalliance-1.0.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-codec-1.9.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-codec-1.9.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-collections-3.2.2.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-collections-3.2.2.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-configuration-1.10.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-configuration-1.10.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-io-2.4.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-io-2.4.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-jxpath-1.3.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-jxpath-1.3.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-lang-2.6.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-lang-2.6.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-lang3-3.4.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-lang3-3.4.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-logging-1.2.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\commons-logging-1.2.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\controls-0.0.1.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\controls-0.0.1.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\core-0.0.1.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\core-0.0.1.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\guava-16.0.1.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\guava-16.0.1.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\guice-4.0.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\guice-4.0.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\httpclient-4.5.1.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\httpclient-4.5.1.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\httpcore-4.4.4.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\httpcore-4.4.4.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\javax.inject-1.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\javax.inject-1.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\modules-0.0.1.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\modules-0.0.1.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\org.eclipse.jdt.annotation-2.0.0.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\org.eclipse.jdt.annotation-2.0.0.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\slf4j-api-1.7.14.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\slf4j-api-1.7.14.jar
Signing (BLOB) C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\slf4j-simple-1.7.14.jar
Signed as C:\Users\FibreFoX\Downloads\Posterer-master\App\target\jfx\web\lib\slf4j-simple-1.7.14.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Posterer .......................................... SUCCESS [0.000s]
[INFO] Core .............................................. SUCCESS [3.025s]
[INFO] Modules implementing functionality with specific libraries  SUCCESS [3.946s]
[INFO] Posterer Controls ................................. SUCCESS [1.156s]
[INFO] Application ....................................... SUCCESS [12.986s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.144s
[INFO] Finished at: Fri Feb 12 20:32:17 CET 2016
[INFO] Final Memory: 24M/253M
[INFO] ------------------------------------------------------------------------
```

**Comment by FibreFoX** [comment]
@technosf Just to clear some things up: what JDK are you using?

**Comment by technosf** [comment]
1.8...

Sometime you need a second pair of eyes. That it worked for you, I thought to _clean _the project. Bingo.

Again, thank you for taking jfx and running with it

**Comment by FibreFoX** [comment]
:+1:
