### ISSUE TITLE
Building RPM on CentOS does not work

### ISSUE THREAD

**Issue by FibreFoX** [javafx-maven-plugin/javafx-maven-plugin#205]
After discussing the problem with the SO-user on this topic: http://stackoverflow.com/q/37178020/1961102

Generating RPM-package on CentOS-system does not work, because still existing bug of native launcher configuration file. [The workaround](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/30b56fff864dc8ec05b302e62c29e7ae9d000289/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L561) seems to not get activated

**Comment by FibreFoX** [comment]
Installed state
![virtualbox_centos-jmp_15_05_2016_16_48_16](https://cloud.githubusercontent.com/assets/1042579/15274895/2aba02ee-1abe-11e6-839d-264e65bf18c3.png)

Modified state (manually doing workaround)
![virtualbox_centos-jmp_15_05_2016_16_50_17](https://cloud.githubusercontent.com/assets/1042579/15274897/2f38b0ae-1abe-11e6-9a83-4a21baf24198.png)

**Comment by FibreFoX** [comment]
User submitted example-project: https://github.com/gclouds/simplejavafxApp

**Comment by FibreFoX** [comment]
Everytime I'm debugging something, I am learning something new!
It seems, that the image-bundler is called within the installer-bundler: https://github.com/teamfx/openjfx-8u-dev-rt/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/linux/LinuxRpmBundler.java#L257

This means the workaround created by me is solely usable for "linux.app", "windows.app" and "mac.app" ... which is really confusing because it worked before ... needs some time to find out why this worked for me before, and if the behaviour was changed.

**Comment by FibreFoX** [comment]
Reference: https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/124

**Comment by gclouds** [comment]
is there any other way by that i can generate working rpm for CENTOS?

**Comment by FibreFoX** [comment]
Hi @gclouds , 
as I have told you via e-mail, you have to set appName containing something without a dot. Please take a look at the [simplejavafxApp](https://github.com/gclouds/simplejavafxApp), which I have updated to a working state. I can build working RPM-file on my CentOS-system.

**Comment by FibreFoX** [comment]
Hi @gclouds ,

I have created a now working SNAPSHOT-version of this plugin. Please add this to your pom.xml:
```xml
<pluginRepositories>
    <pluginRepository>
        <id>oss-sonatype-snapshots</id>
        <url>https://oss.sonatype.org/content/groups/public/</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </pluginRepository>
</pluginRepositories>
```

And please change the version of the used javafx-maven-plugin to `8.5.0-SNAPSHOT`.

The fix now does the same as the workaround for issue #124, but now for installers too (hopefully)

**Comment by FibreFoX** [comment]
ping @gclouds 

This will be closed soon as fixed (with pull-request #206 ) when no further feedback gets provided.

**Comment by FibreFoX** [comment]
After the latest commit inside that PR, this now does work for me on CentOS.

**Comment by gclouds** [comment]
trying to build the software but getting below error first build successful

[ERROR] Failed to execute goal com.zenjava:javafx-maven-plugin:8.4.0:jar (jar) on project TrueChipGUI: Unable to create app lib dir: C:\Users\gauravsi\Documents\AllWs\new\TrueChipGUI\target\jfx\app\lib -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.zenjava:javafx-maven-plugin:8.4.0:jar (jar) on project TrueChipGUI: Unable to create app lib dir: C:\Users\gauravsi\Documents\AllWs\new\TrueChipGUI\target\jfx\app\lib
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:364)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:198)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to create app lib dir: C:\Users\gauravsi\Documents\AllWs\new\TrueChipGUI\target\jfx\app\lib
	at com.zenjava.javafx.maven.plugin.JarMojo.execute(JarMojo.java:161)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 24 more

**Comment by FibreFoX** [comment]
First of all, please upgrade to latest plugin version: 8.5.0
Second: please read the message of the exception: the plugin is unable to create some folder, make sure the user is allowed to write there, sometimes it helps to move the project into some other folder with a less deep folder-structure.

-> no bug as far as i can see (and if so, please make a NEW issue-ticket)

**Comment by gclouds** [comment]
Thanks, this issue is resolved now(restarted the system and deleted the folder manually), may be its eclipse issue, bcoz after creating first successful build I encountered the problem.
