### ISSUE TITLE
build failed when there is no target/classes folder

### ISSUE THREAD

**Issue by 4ndrej** [javafx-maven-plugin/javafx-maven-plugin#233]
`
[ERROR] Failed to execute goal com.zenjava:javafx-maven-plugin:8.5.0:build-jar (create-jfxjar) on project client: Unable to build JFX JAR for application: Error: Failed to create jar file client-0.0.1-SNAPSHOT-jfx.jar: Input folder does not exist [/home/andrej/ws/client/target/classes] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.zenjava:javafx-maven-plugin:8.5.0:build-jar (create-jfxjar) on project bsign-proxy-client: Unable to build JFX JAR for application
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to build JFX JAR for application
	at com.zenjava.javafx.maven.plugin.JarMojo.execute(JarMojo.java:239)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: com.sun.javafx.tools.packager.PackagerException: Error: Failed to create jar file client-0.0.1-SNAPSHOT-jfx.jar
	at com.sun.javafx.tools.packager.PackagerLib.packageAsJar(PackagerLib.java:301)
	at com.zenjava.javafx.maven.plugin.JarMojo.execute(JarMojo.java:237)
	... 22 more
Caused by: java.io.FileNotFoundException: Input folder does not exist [/home/andrej/ws/client/target/classes]
	at com.sun.javafx.tools.packager.PackagerLib.jar(PackagerLib.java:743)
	at com.sun.javafx.tools.packager.PackagerLib.jar(PackagerLib.java:685)
	at com.sun.javafx.tools.packager.PackagerLib.packageAsJar(PackagerLib.java:297)
	... 23 more
`

this happened when there is no sources at all, so the target/classes folder does not exist. I know this is not very common but the javafx-maven-plugin could do mkdir -p before attempting to create the target jar file.

**Comment by FibreFoX** [comment]
Nope, this plugin depends on the outcome of the maven-jar-plugin, which is responsible of having `target/classes` being created. This is no bug!
How did you reach that exception anyway?

**Comment by FibreFoX** [comment]
I will add some warning to the plugin.

**Comment by 4ndrej** [comment]
@FibreFoX well, I was debugging apache cxf bug (cxf is validating all src/main/resources/wsdl files whether it's referenced in the project or not) and was making sort of minimal project for narow the search. So I ended having empty src/main/java folder.

**Comment by FibreFoX** [comment]
@4ndrej this is available as snapshot-version: `8.7.1-SNAPSHOT`, can you try this version? (don't forget to adjust your repositories-section)

**Comment by 4ndrej** [comment]
works great for me,
it jist created the empty classes folder and generated client/target/jfx/app/client-0.0.1-SNAPSHOT-jfx.jar with only META-INF/MANIFEST.MF file
thank you
