### ISSUE TITLE
Including jar from local repository?

### ISSUE THREAD

**Issue by srynoname** [javafx-maven-plugin/javafx-maven-plugin#27]
Hello,

I need to use a jar file from a local repository (javafx-dialogs, see [1]) in my project. This jar shall also be included in a jar file generated by running jfx:build-jar. However, when running the generated jar file, a NullPointerException occurs:

 >java -jar testproject-0.0.1-SNAPSHOT-jfx.jar
 Exception in Application start method
 java.lang.reflect.InvocationTargetException
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
         at java.lang.reflect.Method.invoke(Unknown Source)
         at com.javafx.main.Main.launchApp(Main.java:642)
         at com.javafx.main.Main.main(Main.java:805)
 Caused by: java.lang.RuntimeException: Exception in Application start method
         at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:403)
         at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:47)
         at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:115)
         at java.lang.Thread.run(Unknown Source)
 Caused by: java.lang.NullPointerException
         at javafx.scene.control.Dialogs$FXDialog$3.run(Dialogs.java:1144)
         at java.security.AccessController.doPrivileged(Native Method)
         at javafx.scene.control.Dialogs$FXDialog.<init>(Dialogs.java:1142)
         at javafx.scene.control.Dialogs$FXDialog.<init>(Dialogs.java:1088)
         at javafx.scene.control.Dialogs$DialogTemplate.<init>(Dialogs.java:616)
         at javafx.scene.control.Dialogs.showSimpleContentDialog(Dialogs.java:494)
         at javafx.scene.control.Dialogs.showConfirmDialog(Dialogs.java:226)
         at javafx.scene.control.Dialogs.showConfirmDialog(Dialogs.java:217)
         at Main.start(Main.java:20)
         at com.sun.javafx.application.LauncherImpl$5.run(LauncherImpl.java:319)
         at com.sun.javafx.application.PlatformImpl$5.run(PlatformImpl.java:215)
         at com.sun.javafx.application.PlatformImpl$4$1.run(PlatformImpl.java:179)
         at com.sun.javafx.application.PlatformImpl$4$1.run(PlatformImpl.java:176)
         at java.security.AccessController.doPrivileged(Native Method)
         at com.sun.javafx.application.PlatformImpl$4.run(PlatformImpl.java:176)
         at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
         at com.sun.glass.ui.win.WinApplication.access$100(WinApplication.java:29)
         at com.sun.glass.ui.win.WinApplication$3$1.run(WinApplication.java:73)
         ... 1 more

Everything works fine, when the project is run directly from the IDE (Eclipse). A sample project can be found at https://code.google.com/p/codestefan/source/browse/#svn%2Ftestproject%253Fstate%253Dclosed

Any hint on how to get a working jar which includes javafx-dialogs? Thanks :-)

Hint:
Note that javafx-dialogs is at least detected during creation of the jar file:
 [INFO] <<< javafx-maven-plugin:1.5:build-jar (default-cli) @ testproject <<<
 [INFO] 
 [INFO] --- javafx-maven-plugin:1.5:build-jar (default-cli) @ testproject ---
 [INFO] Assembling JavaFX executable JAR to 'C:\Users\myuser\Desktop\maventest\target\testproject-0.0.1-SNAPSHOT-jfx.jar'
 [INFO] Unpacking module dependendencies to: C:\Users\myuser\Desktop\maventest\target\jfx-dependencies
 [INFO] Unpacking C:\Users\myuser\.m2\repository\javafx\dialogs\0.0.3\dialogs-0.0.3.jar to C:\Users\myuser\Desktop\maventest\target\jfx-dependencies with includes "" and excludes ""
 [INFO] Java home is: C:\Program Files (x86)\Java\jdk1.7.0_21\jre
 [INFO] ------------------------------------------------------------------------
 [INFO] BUILD SUCCESS

[1] https://github.com/marcojakob/javafx-ui-sandbox/tree/master/javafx-dialogs/dist

**Comment by FibreFoX** [comment]
```So, can be closed now :-)```
