### ISSUE TITLE
Skipping 'EXE Installer' because of configuration error

### ISSUE THREAD

**Issue by McRender** [javafx-maven-plugin/javafx-maven-plugin#275]
I'am trying to build a native installer for my JavaFX application with the aid of your maven plugin. When using version 8.7.0 everything works as expected. When switching to version 8.8.1 I get the following errors building in Netbeans 8.2:

```
--- javafx-maven-plugin:8.8.1:build-native (create-native) @ HelloJavaFXMaven ---
Building Native Installers
Add E:\Users\McRender\Documents\NetBeansProjects\HelloJavaFXMaven\target\jfx\app\HelloJavaFXMaven-1.0-SNAPSHOT-jfx.jar file to application resources.
Running [C:\Program Files\Java\jdk1.8.0_121\jre\bin\java, -version]
Creating app bundle: HelloJavaFXMaven-1.0-SNAPSHOT in E:\Users\McRender\Documents\NetBeansProjects\HelloJavaFXMaven\target\jfx\native
  Using default package resource [application icon]  (add package/windows/HelloJavaFXMaven-1.0-SNAPSHOT.ico to the class path to customize)
Running [C:\Users\McRender\AppData\Local\Temp\iconswap8906608383463270919.exe, C:\Users\McRender\AppData\Local\Temp\fxbundler4152686819734722549\windows\HelloJavaFXMaven-1.0-SNAPSHOT.ico, E:\Users\McRender\Documents\NetBeansProjects\HelloJavaFXMaven\target\jfx\native\HelloJavaFXMaven-1.0-SNAPSHOT\HelloJavaFXMaven-1.0-SNAPSHOT.exe]
Icon File Name: C:\Users\McRender\AppData\Local\Temp\fxbundler4152686819734722549\windows\HelloJavaFXMaven-1.0-SNAPSHOT.ico
Executable File Name: E:\Users\McRender\Documents\NetBeansProjects\HelloJavaFXMaven\target\jfx\native\HelloJavaFXMaven-1.0-SNAPSHOT\HelloJavaFXMaven-1.0-SNAPSHOT.exe
Result application bundle: E:\Users\McRender\Documents\NetBeansProjects\HelloJavaFXMaven\target\jfx\native
  Config files are saved to C:\Users\McRender\AppData\Local\Temp\fxbundler4152686819734722549\windows. Use them to customize package.
Running [C:\Program Files\Java\jdk1.8.0_121\jre\bin\java, -version]
Skipping 'EXE Installer' because of configuration error 'java.lang.NullPointerException'
Advice to fix: null
Running [C:\Program Files\Java\jdk1.8.0_121\jre\bin\java, -version]
Running [C:\Program Files (x86)\WiX Toolset v3.10\bin\candle.exe, /?]
  Detected [C:\Program Files (x86)\WiX Toolset v3.10\bin\candle.exe] version [3.1]
Running [C:\Program Files (x86)\WiX Toolset v3.10\bin\light.exe, /?]
  Detected [C:\Program Files (x86)\WiX Toolset v3.10\bin\light.exe] version [3.1]
At least one type of shortcut is required. Enabling menu shortcut.
  Using default package resource [application icon]  (add package/windows/HelloJavaFXMaven-1.0-SNAPSHOT.ico to the class path to customize)
Running [C:\Users\McRender\AppData\Local\Temp\iconswap3760013983579295695.exe, C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\windows\HelloJavaFXMaven-1.0-SNAPSHOT.ico, C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\images\win-msi.image\HelloJavaFXMaven-1.0-SNAPSHOT\HelloJavaFXMaven-1.0-SNAPSHOT.exe]
Icon File Name: C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\windows\HelloJavaFXMaven-1.0-SNAPSHOT.ico
Executable File Name: C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\images\win-msi.image\HelloJavaFXMaven-1.0-SNAPSHOT\HelloJavaFXMaven-1.0-SNAPSHOT.exe
  Config files are saved to C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\windows. Use them to customize package.
Generated product GUID: f9988bc0-5f4c-455f-b4e1-0842385470c6
  Using default package resource [WiX config file]  (add package/windows/HelloJavaFXMaven-1.0-SNAPSHOT.wxs to the class path to customize)
Using default package resource [script to run after application image is populated]  (add package/windows/HelloJavaFXMaven-1.0-SNAPSHOT-post-image.wsf to the class path to customize)
Preparing MSI config: E:\Users\McRender\Documents\NetBeansProjects\HelloJavaFXMaven\target\jfx\native\HelloJavaFXMaven-1.0-SNAPSHOT.msi
Running [C:\Program Files (x86)\WiX Toolset v3.10\bin\candle.exe, -nologo, C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\windows\HelloJavaFXMaven-1.0-SNAPSHOT.wxs, -ext, WixUtilExtension, -out, C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\tmp\HelloJavaFXMaven-1.0-SNAPSHOT.wixobj] in C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\images\win-msi.image\HelloJavaFXMaven-1.0-SNAPSHOT
HelloJavaFXMaven-1.0-SNAPSHOT.wxs
C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\windows\HelloJavaFXMaven-1.0-SNAPSHOT.wxs(4) : error CNDL0108 : The Product/@Version attribute's value, 'APPLICATION_VERSION', is not a valid version.  Legal version values should look like 'x.x.x.x' where x is an integer from 0 to 65534.
C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\windows\HelloJavaFXMaven-1.0-SNAPSHOT.wxs(4) : error CNDL0010 : The Product/@Version attribute was not found; it is required.
java.io.IOException: Exec failed with code 10 command [[C:\Program Files (x86)\WiX Toolset v3.10\bin\candle.exe, -nologo, C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\windows\HelloJavaFXMaven-1.0-SNAPSHOT.wxs, -ext, WixUtilExtension, -out, C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\tmp\HelloJavaFXMaven-1.0-SNAPSHOT.wixobj] in C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\images\win-msi.image\HelloJavaFXMaven-1.0-SNAPSHOT
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:165)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:138)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:132)
	at com.oracle.tools.packager.windows.WinMsiBundler.buildMSI(WinMsiBundler.java:1063)
	at com.oracle.tools.packager.windows.WinMsiBundler.bundle(WinMsiBundler.java:510)
	at com.oracle.tools.packager.windows.WinMsiBundler.execute(WinMsiBundler.java:232)
	at com.zenjava.javafx.maven.plugin.NativeMojo.execute(NativeMojo.java:695)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
  Config files are saved to C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\windows. Use them to customize package.
Skipping 'WebStart JNLP Bundler' because of configuration error 'No OutFile Specificed'
Advice to fix: Please specify the name of the JNLP Outut file in 'jnlp.outfile'
```

I can detect two main problems:

1. Skipping 'EXE Installer' because of configuration error 'java.lang.NullPointerException'
Advice to fix: null

2. java.io.IOException: Exec failed with code 10 command [[C:\Program Files (x86)\WiX Toolset v3.10\bin\candle.exe, -nologo, C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\windows\HelloJavaFXMaven-1.0-SNAPSHOT.wxs, -ext, WixUtilExtension, -out, C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\tmp\HelloJavaFXMaven-1.0-SNAPSHOT.wixobj] in C:\Users\McRender\AppData\Local\Temp\fxbundler5079928049502351254\images\win-msi.image\HelloJavaFXMaven-1.0-SNAPSHOT

Any idea what causes the build to fail? For testing puropse I just created a new JavaFX Maven application within Netbeans and added the following lines to my pom.xml:

```xml
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.8.1</version>
    <configuration>
        <mainClass>com.mycompany.hellojavafxmaven.MainApp</mainClass>
        <verbose>true</verbose>
    </configuration>
    <executions>
        <execution>
            <!-- required before build-native -->
            <id>create-jfxjar</id>
            <phase>package</phase>
            <goals>
                <goal>build-jar</goal>
            </goals>
        </execution>
        <execution>
            <id>create-native</id>
            <phase>package</phase>
            <goals>
                <goal>build-native</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Pleas let me know if you need any further informations.

**Comment by FibreFoX** [comment]
Hi, can you try to set `<skipNativeVersionNumberSanitizing>true</skipNativeVersionNumberSanitizing>` ? Maybe there is a problem with the new feature which is active by default.

**Comment by McRender** [comment]
Adding the propsed tag to the confiuration does not solve the issue:

```
<plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.8.1</version>
                <configuration>
                        <mainClass>com.mycompany.hellojavafxmaven.MainApp</mainClass>
                        <verbose>true</verbose>
                        <skipNativeVersionNumberSanitizing>true</skipNativeVersionNumberSanitizing>
                </configuration>
                <executions>
                        <execution>
                                <!-- required before build-native -->
                                <id>create-jfxjar</id>
                                <phase>package</phase>
                                <goals>
                                        <goal>build-jar</goal>
                                </goals>
                        </execution>
                        <execution>
                                <id>create-native</id>
                                <phase>package</phase>
                                <goals>
                                        <goal>build-native</goal>
                                </goals>
                        </execution>
                </executions>
            </plugin>
```

```
--- javafx-maven-plugin:8.8.1:build-native (create-native) @ HelloJavaFXMaven ---
Building Native Installers
Add E:\Users\McRender\Documents\NetBeansProjects\HelloJavaFXMaven\target\jfx\app\HelloJavaFXMaven-1.0-SNAPSHOT-jfx.jar file to application resources.
Running [C:\Program Files\Java\jdk1.8.0_121\jre\bin\java, -version]
Creating app bundle: HelloJavaFXMaven-1.0-SNAPSHOT in E:\Users\McRender\Documents\NetBeansProjects\HelloJavaFXMaven\target\jfx\native
  Using default package resource [application icon]  (add package/windows/HelloJavaFXMaven-1.0-SNAPSHOT.ico to the class path to customize)
Running [C:\Users\McRender\AppData\Local\Temp\iconswap4196457381354559540.exe, C:\Users\McRender\AppData\Local\Temp\fxbundler5776323870811206798\windows\HelloJavaFXMaven-1.0-SNAPSHOT.ico, E:\Users\McRender\Documents\NetBeansProjects\HelloJavaFXMaven\target\jfx\native\HelloJavaFXMaven-1.0-SNAPSHOT\HelloJavaFXMaven-1.0-SNAPSHOT.exe]
Icon File Name: C:\Users\McRender\AppData\Local\Temp\fxbundler5776323870811206798\windows\HelloJavaFXMaven-1.0-SNAPSHOT.ico
Executable File Name: E:\Users\McRender\Documents\NetBeansProjects\HelloJavaFXMaven\target\jfx\native\HelloJavaFXMaven-1.0-SNAPSHOT\HelloJavaFXMaven-1.0-SNAPSHOT.exe
Result application bundle: E:\Users\McRender\Documents\NetBeansProjects\HelloJavaFXMaven\target\jfx\native
  Config files are saved to C:\Users\McRender\AppData\Local\Temp\fxbundler5776323870811206798\windows. Use them to customize package.
Running [C:\Program Files\Java\jdk1.8.0_121\jre\bin\java, -version]
Skipping 'EXE Installer' because of configuration error 'java.lang.NullPointerException'
Advice to fix: null
Running [C:\Program Files\Java\jdk1.8.0_121\jre\bin\java, -version]
Running [C:\Program Files (x86)\WiX Toolset v3.10\bin\candle.exe, /?]
  Detected [C:\Program Files (x86)\WiX Toolset v3.10\bin\candle.exe] version [3.1]
Running [C:\Program Files (x86)\WiX Toolset v3.10\bin\light.exe, /?]
  Detected [C:\Program Files (x86)\WiX Toolset v3.10\bin\light.exe] version [3.1]
At least one type of shortcut is required. Enabling menu shortcut.
  Using default package resource [application icon]  (add package/windows/HelloJavaFXMaven-1.0-SNAPSHOT.ico to the class path to customize)
Running [C:\Users\McRender\AppData\Local\Temp\iconswap5294050082509079679.exe, C:\Users\McRender\AppData\Local\Temp\fxbundler5738390030557322266\windows\HelloJavaFXMaven-1.0-SNAPSHOT.ico, C:\Users\McRender\AppData\Local\Temp\fxbundler5738390030557322266\images\win-msi.image\HelloJavaFXMaven-1.0-SNAPSHOT\HelloJavaFXMaven-1.0-SNAPSHOT.exe]
Icon File Name: C:\Users\McRender\AppData\Local\Temp\fxbundler5738390030557322266\windows\HelloJavaFXMaven-1.0-SNAPSHOT.ico
Executable File Name: C:\Users\McRender\AppData\Local\Temp\fxbundler5738390030557322266\images\win-msi.image\HelloJavaFXMaven-1.0-SNAPSHOT\HelloJavaFXMaven-1.0-SNAPSHOT.exe
  Config files are saved to C:\Users\McRender\AppData\Local\Temp\fxbundler5738390030557322266\windows. Use them to customize package.
Generated product GUID: e1176213-0798-495c-ac0b-c18928bc28a5
  Using default package resource [WiX config file]  (add package/windows/HelloJavaFXMaven-1.0-SNAPSHOT.wxs to the class path to customize)
Using default package resource [script to run after application image is populated]  (add package/windows/HelloJavaFXMaven-1.0-SNAPSHOT-post-image.wsf to the class path to customize)
Preparing MSI config: E:\Users\McRender\Documents\NetBeansProjects\HelloJavaFXMaven\target\jfx\native\HelloJavaFXMaven-1.0-SNAPSHOT.msi
Running [C:\Program Files (x86)\WiX Toolset v3.10\bin\candle.exe, -nologo, C:\Users\McRender\AppData\Local\Temp\fxbundler5738390030557322266\windows\HelloJavaFXMaven-1.0-SNAPSHOT.wxs, -ext, WixUtilExtension, -out, C:\Users\McRender\AppData\Local\Temp\fxbundler5738390030557322266\tmp\HelloJavaFXMaven-1.0-SNAPSHOT.wixobj] in C:\Users\McRender\AppData\Local\Temp\fxbundler5738390030557322266\images\win-msi.image\HelloJavaFXMaven-1.0-SNAPSHOT
HelloJavaFXMaven-1.0-SNAPSHOT.wxs
C:\Users\McRender\AppData\Local\Temp\fxbundler5738390030557322266\windows\HelloJavaFXMaven-1.0-SNAPSHOT.wxs(4) : error CNDL0108 : The Product/@Version attribute's value, 'APPLICATION_VERSION', is not a valid version.  Legal version values should look like 'x.x.x.x' where x is an integer from 0 to 65534.
C:\Users\McRender\AppData\Local\Temp\fxbundler5738390030557322266\windows\HelloJavaFXMaven-1.0-SNAPSHOT.wxs(4) : error CNDL0010 : The Product/@Version attribute was not found; it is required.
java.io.IOException: Exec failed with code 10 command [[C:\Program Files (x86)\WiX Toolset v3.10\bin\candle.exe, -nologo, C:\Users\McRender\AppData\Local\Temp\fxbundler5738390030557322266\windows\HelloJavaFXMaven-1.0-SNAPSHOT.wxs, -ext, WixUtilExtension, -out, C:\Users\McRender\AppData\Local\Temp\fxbundler5738390030557322266\tmp\HelloJavaFXMaven-1.0-SNAPSHOT.wixobj] in C:\Users\McRender\AppData\Local\Temp\fxbundler5738390030557322266\images\win-msi.image\HelloJavaFXMaven-1.0-SNAPSHOT
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:165)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:138)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:132)
	at com.oracle.tools.packager.windows.WinMsiBundler.buildMSI(WinMsiBundler.java:1063)
	at com.oracle.tools.packager.windows.WinMsiBundler.bundle(WinMsiBundler.java:510)
	at com.oracle.tools.packager.windows.WinMsiBundler.execute(WinMsiBundler.java:232)
	at com.zenjava.javafx.maven.plugin.NativeMojo.execute(NativeMojo.java:695)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
  Config files are saved to C:\Users\McRender\AppData\Local\Temp\fxbundler5738390030557322266\windows. Use them to customize package.
Skipping 'WebStart JNLP Bundler' because of configuration error 'No OutFile Specificed'
Advice to fix: Please specify the name of the JNLP Outut file in 'jnlp.outfile'
```

**Comment by FibreFoX** [comment]
Greetings from Germany ;)

Can you create a small stripped down example for this?

**Comment by McRender** [comment]
Sure... Just use the same project I've uploaded for the JNI issue :-). Do you want me to add it here aswell?

**Comment by FibreFoX** [comment]
Nope, I'm on it.

**Comment by FibreFoX** [comment]
Ha, there seems to be a problem with the version ... again :( the new feature does not seem to work as expected ... seems likely to be a case of "just another patch-release".

The problem seems to be the created `.cfg`-file which contains this:
```ini
[Application]
app.name=JSSCNativeLab-1.0-SNAPSHOT
app.mainjar=JSSCNativeLab-1.0-SNAPSHOT-jfx.jar
app.version=null
app.preferences.id=com/mycompany/jsscnativelab
app.mainclass=com/mycompany/jsscnativelab/MainApp
app.classpath=lib/jssc-2.8.0.jar
app.runtime=$APPDIR\runtime
app.identifier=com.mycompany.jsscnativelab

[JVMOptions]

[JVMUserOptions]

[ArgOptions]
```
The problem is this entry: `app.version=null`

**Comment by FibreFoX** [comment]
Found the problem :( it is missing because I reworked all mojo-parameters to be accessible via maven-properties ... interesting ... thanks for finding and reporting this bug !

**Comment by McRender** [comment]
I can confirm this on my side:

```
[Application]
app.name=JSSCNativeLab-1.0-SNAPSHOT
app.mainjar=JSSCNativeLab-1.0-SNAPSHOT-jfx.jar
app.version=null
app.preferences.id=com/mycompany/jsscnativelab
app.mainclass=com/mycompany/jsscnativelab/MainApp
app.classpath=lib/jssc-2.8.0.jar
app.runtime=$APPDIR\runtime
app.identifier=com.mycompany.jsscnativelab

[JVMOptions]

[JVMUserOptions]

[ArgOptions]
```

**Comment by McRender** [comment]
Allways a pleasure. It's all about giving & taking :-)

**Comment by FibreFoX** [comment]
@McRender can you re-try using 8.8.2-SNAPSHOT? Please take care to configure your pom.xml to get the sonatype-repository for snapshots

**Comment by McRender** [comment]
I've added this to my settings.xml and tried to download the snapshot:

```
<settings>
    <profiles>
      <profile>
         <id>allow-snapshots</id>
         <activation>
             <activeByDefault>true</activeByDefault>
         </activation>
         <repositories>
           <repository>
             <id>snapshots-repo</id>
             <url>https://oss.sonatype.org/content/repositories/snapshots</url>
             <releases><enabled>false</enabled></releases>
             <snapshots><enabled>true</enabled></snapshots>
           </repository>
         </repositories>
       </profile>
    </profiles>
</settings>
```

But I can't resolve the dependencies. Did I miss something?

**Comment by FibreFoX** [comment]
You did miss something, because you have to add sonatype as pluginRepository:

```xml
<pluginRepositories>
    <pluginRepository>
        <id>oss-sonatype-snapshots</id>
        <url>https://oss.sonatype.org/content/groups/public/</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </pluginRepository>
</pluginRepositories>
```

**Comment by McRender** [comment]
Thanks for pointing me in the right dirction. I think we have a geen light again! 

![grafik](https://cloud.githubusercontent.com/assets/5795337/22774281/be51fc34-eea6-11e6-95fa-8d908425a190.png)

![grafik](https://cloud.githubusercontent.com/assets/5795337/22774302/d1bf0f14-eea6-11e6-9122-6ee5c90110f4.png)

**Comment by FibreFoX** [comment]
Fixed version got released, but takes it time to hit maven-central.
