### ISSUE TITLE
Mac High Sierra Native Build Issue - Custom Volume Icon

### ISSUE THREAD

**Issue by dustintbrown** [javafx-maven-plugin/javafx-maven-plugin#312]
It looks like the hdiutil command is creating APFS file system DMGs instead of HFS+ file systems. I believe the setting of the custom icon is failing due to this.
```
    Config files are saved to /var/folders/_x/bjbbfjb15917fvwm06zytrs40000gn/T/fxbundler2701455864877164035/macosx. Use them to customize package.
  Using default package resource [dmg background]  (add package/macosx/My Application-background.png to the class path to customize)
  Using custom package resource [volume icon]  (loaded from package/macosx/My Application-volume.icns)
Using default package resource [script to run after application image is populated]  (add package/macosx/My Application-post-image.sh to the class path to customize)
Preparing dmg setup: /var/folders/_x/bjbbfjb15917fvwm06zytrs40000gn/T/fxbundler2701455864877164035/macosx/My Application-dmg-setup.scpt
  Using default package resource [DMG setup script]  (add package/macosx/My Application-dmg-setup.scpt to the class path to customize)
 Creating DMG file: /Users/brownd/idea/prime-edits/My Application App/target/jfx/native/My Application-2.5.12.dmg
Running [/usr/bin/hdiutil, create, -quiet, -srcfolder, /var/folders/_x/bjbbfjb15917fvwm06zytrs40000gn/T/fxbundler2701455864877164035/images/image-2578499420009829112, -volname, My Application, -ov, /var/folders/_x/bjbbfjb15917fvwm06zytrs40000gn/T/fxbundler2701455864877164035/images/My Application-tmp.dmg, -format, UDRW]
Running [/usr/bin/hdiutil, attach, /var/folders/_x/bjbbfjb15917fvwm06zytrs40000gn/T/fxbundler2701455864877164035/images/My Application-tmp.dmg, -quiet, -mountroot, /var/folders/_x/bjbbfjb15917fvwm06zytrs40000gn/T/fxbundler2701455864877164035/images]
Running [osascript, /var/folders/_x/bjbbfjb15917fvwm06zytrs40000gn/T/fxbundler2701455864877164035/macosx/My Application-dmg-setup.scpt]
Running [/usr/bin/SetFile, -c, icnC, /var/folders/_x/bjbbfjb15917fvwm06zytrs40000gn/T/fxbundler2701455864877164035/images/My Application/.VolumeIcon.icns]
ERROR: File Not Found. (-43)  on file: /var/folders/_x/bjbbfjb15917fvwm06zytrs40000gn/T/fxbundler2701455864877164035/images/My Application/.VolumeIcon.icns 
java.io.IOException: Exec failed with code 2 command [[/usr/bin/SetFile, -c, icnC, /var/folders/_x/bjbbfjb15917fvwm06zytrs40000gn/T/fxbundler2701455864877164035/images/My Application/.VolumeIcon.icns] in unspecified directory
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:165)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:138)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:132)
	at com.oracle.tools.packager.mac.MacDmgBundler.buildDMG(MacDmgBundler.java:391)
	at com.oracle.tools.packager.mac.MacDmgBundler.bundle(MacDmgBundler.java:92)
	at com.oracle.tools.packager.mac.MacDmgBundler.execute(MacDmgBundler.java:549)
	at com.zenjava.javafx.maven.plugin.NativeMojo.execute(NativeMojo.java:695)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

**Comment by dustintbrown** [comment]
Looks like may be related to native packager tools: https://stackoverflow.com/questions/46515301/icns-file-not-found-error-with-javapackager-on-macos-high-sierra

**Comment by FibreFoX** [comment]
Please report this to Oracle, as this is a problem of the underlying `javapackager`:
http://bugreport.java.com/


    Type: Bug
    Product/Category: JavaFX
    Subcategory: Packager

When you have some feedback from oracle, please report it back here, so others can find this (and I can check when it gets fixed, ...or getting closed as "won't fix").

Just refere to javapackager when reporting, but you can add this issue as some reference.

**Comment by peterlynch** [comment]
Its this bug: https://bugs.openjdk.java.net/browse/JDK-8190758

Due for release mid Jan 2018.

**Comment by FibreFoX** [comment]
@peterlynch thanks for reportings this here :) helps to keep track of this

**Comment by FibreFoX** [comment]
@peterlynch seems to be fixed with current 1.8.0u162, can you update and check this again?
https://bugs.openjdk.java.net/browse/JDK-8192002
http://www.oracle.com/technetwork/java/javase/2col/8u162-bugfixes-4021468.html

**Comment by craigday** [comment]
I just ran across this, and u162 does appear to fix the problem.

**Comment by FibreFoX** [comment]
Thanks for the good news @craigday ;) will close this.

**Comment by sonvirgo** [comment]
no doesn't fix
```
echo $(/usr/libexec/java_home)
/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home

ERROR: File Not Found. (-43)  on file: /var/folders/3t/h7q7rcmx27v237784lpynxc00000gn/T/fxbundler5144773095562248847/images/Agent/.VolumeIcon.icns 
Exec failed with code 2 command [[/usr/bin/SetFile, -c, icnC, /var/folders/3t/h7q7rcmx27v237784lpynxc00000gn/T/fxbundler5144773095562248847/images/Agent/.VolumeIcon.icns] in unspecified directory
```

**Comment by nyholku** [comment]
I can also confirm that the bug fix (in my case jdk1.8.0_181) does not completely fix this. I get the exact same error (ERROR: File Not Found. (-43)  ....  /.VolumeIcon.icns ).

However I noticed an interesting and weird phenomenon. 

I have custom 'myproject-dmg-setup.scpt'  (well, it is not really custom, just plain vanilla as created by javapackager).

If I edit that file so that the script fails (for example add X to the first line so it reads 'Xtell') and try to build the build obviously fails at that point. 

However when I remove the X and build again, the build succeeds and the volume icon gets set and all. 

But next build again fails if I do not do this weird trick again.

Strange.

**Comment by nyholku** [comment]
Ok, more testing and I have redact  part of my comment. I was correct in that the jdk1.8.0_181 does not work for me but fiddling with the 'myproject-dmg-setup.scpt' does not actually fix that but it triggers an other part of my build script that sets the dmg icon using SetFileIcon.
