### ISSUE TITLE
resource name cannot contain Chinese?

### ISSUE THREAD

**Issue by fangdong116** [javafx-maven-plugin/javafx-maven-plugin#339]
resource(ie icon) name cannot contain Chinese?
The error message is
java.io.IOException: Exec failed with code 2 command [[C:\Program Files (x86)\Inno Setup 5\iscc.exe, /oD:\project\xiaoka\cloud-stock\cs-client\target\jfx\native, C:\Users\ADMINI~1.XKZ\AppData\Local\Temp\fxbundler388457266493355265\images\win-exe.image\仓数.iss] in C:\Users\ADMINI~1.XKZ\AppData\Local\Temp\fxbundler388457266493355265\images\win-exe.image
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:165)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:138)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:132)
	at com.oracle.tools.packager.windows.WinExeBundler.buildEXE(WinExeBundler.java:697)
	at com.oracle.tools.packager.windows.WinExeBundler.bundle(WinExeBundler.java:366)
	at com.oracle.tools.packager.windows.WinExeBundler.execute(WinExeBundler.java:173)
	at com.zenjava.javafx.maven.plugin.NativeMojo.execute(NativeMojo.java:695)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by FibreFoX** [comment]
Closed as duplicate, please see here for more details: https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/209#issuecomment-313069963
