### ISSUE TITLE
How to use this plugin with springboot

### ISSUE THREAD

**Issue by xinkunZ** [javafx-maven-plugin/javafx-maven-plugin#377]
* I just has a springboot+javafx project
* then I want use this plugin to build a msi installer
* I use this gist https://gist.github.com/ennerf/55838933a15e019d9e62cbac3a2d0304 
* at last, the "target\jfx\app" could not run by "java -jar" with there errors
```
Exception in thread "main" java.lang.IllegalStateException: Failed to get nested archive for entry BOOT-INF/lib/spring-boot-starter-data-jdbc-2.2.1.RELEASE.jar
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:113)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:87)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:69)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.io.IOException: Unable to open nested jar file 'BOOT-INF/lib/spring-boot-starter-data-jdbc-2.2.1.RELEASE.jar'
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:261)
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:247)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:109)
        ... 4 more
Caused by: java.lang.IllegalStateException: Unable to open nested entry 'BOOT-INF/lib/spring-boot-starter-data-jdbc-2.2.1.RELEASE.jar'. It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:287)
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:269)
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:258)
        ... 6 more
```
* It seem this plugin change the content of springboot fat jar??
* please tell me how to fix this!! THANKS!!

**Comment by FibreFoX** [comment]
Instead of having a fat-jar, I strongly sugguest to build a javafx-application, that just contains Spring as a dependency. I did this once myself, will come back to you when I found that project.

**Comment by xinkunZ** [comment]
* I try many times, and found the success way!!!
* I just use a profile to do this, then I can use `mvn install -Pmsi` to create the windows msi
```
  <profiles>
    <profile>
      <id>msi</id>
      <build>
        <plugins>
          <plugin>
          <!-- copy the spring-boot jar to jfx app directory -->
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-antrun-plugin</artifactId>
            <version>1.7</version>
            <executions>
              <execution>
                <id>copy-jfx-app</id>
                <phase>package</phase>
                <goals>
                  <goal>run</goal>
                </goals>
                <configuration>
                  <target name="copy-jfx-app">
                    <copy file="${project.build.directory}/${project.build.finalName}.jar" tofile="${project.build.directory}/jfx/app/${project.build.finalName}-jfx.jar" />
                  </target>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>com.zenjava</groupId>
            <artifactId>javafx-maven-plugin</artifactId>
            <version>8.8.3</version>
            <configuration>
              <needMenu>true</needMenu>
              <needShortcut>true</needShortcut>
              <vendor>your company</vendor>
              <appName>you-app-name</appName>
              <nativeReleaseVersion>3.0</nativeReleaseVersion>
              <!-- change main class to springboot jar launcher -->
              <mainClass>org.springframework.boot.loader.JarLauncher</mainClass>

              <!-- disable default jfx package logic -->
              <updateExistingJar>true</updateExistingJar>
              <skipCopyingDependencies>true</skipCopyingDependencies>
              <useLibFolderContentForManifestClasspath>true</useLibFolderContentForManifestClasspath>
              <bundleArguments>
              <!-- !!MUST SET!!  otherwise your installer will not find and use your ico  -->
                <icon>${project.basedir}/src/main/deploy/package/windows/you-app-name.ico</icon>
              </bundleArguments>
            </configuration>
            <executions>
              <!-- disable default jfx package logic -->
              <execution>
                <id>create-jfxjar</id>
                <phase>none</phase>
                <goals>
                  <goal>build-jar</goal>
                </goals>
              </execution>
              <execution>
                <id>create-jar</id>
                <phase>none</phase>
                <goals>
                  <goal>jar</goal>
                </goals>
              </execution>
              <execution>
                <id>create-native</id>
                <phase>package</phase>
                <goals>
                  <goal>build-native</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
```
