### ISSUE TITLE
Problems with jfx:native

### ISSUE THREAD

**Issue by samuelcguimaraes** [javafx-maven-plugin/javafx-maven-plugin#43]
I get the exception below

```
...
[INFO] Building Native Installers
[INFO] Adding 'deploy' directory to Mojo classpath: W:\SASC FX\SascFx/src/main/deploy
Using base JDK at: C:\Program Files\Java\jdk1.7.0_25\jre
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:22.941s
[INFO] Finished at: Tue Sep 10 11:01:50 BRT 2013
[INFO] Final Memory: 16M/53M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.zenjava:javafx-maven-plugin:2.0:native (default-cli) on project SascFx: Execution default-cli of goal com.zenjava:javafx-maven-plugin:2.0:native failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.zenjava:javafx-maven-plugin:2.0:native (default-cli) on project SascFx: Execution default-cli of goal com.zenjava:javafx-maven-plugin:2.0:native failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.zenjava:javafx-maven-plugin:2.0:native failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.NullPointerException
	at com.sun.javafx.tools.packager.bundlers.BundleParams.getMainApplicationJar(BundleParams.java:390)
	at com.sun.javafx.tools.packager.bundlers.WinAppBundler.doValidate(WinAppBundler.java:59)
	at com.sun.javafx.tools.packager.bundlers.WinAppBundler.validate(WinAppBundler.java:43)
	at com.sun.javafx.tools.packager.bundlers.Bundler.get(Bundler.java:91)
	at com.sun.javafx.tools.packager.PackagerLib.generateNativeBundles(PackagerLib.java:450)
	at com.sun.javafx.tools.packager.PackagerLib.generateDeploymentPackages(PackagerLib.java:435)
	at com.zenjava.javafx.maven.plugin.NativeMojo.execute(NativeMojo.java:167)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

Basically, I have my application pom configured like so:
```
<project ...>
	
	...
 
    <groupId>br.com.sicoobcredinor.sascfx</groupId>
    <artifactId>SascFx</artifactId>
    <name>SascFx</name>

    <packaging>jar</packaging>
    <version>1.0-SNAPSHOT</version>
    
    <organization>
        <!-- Used as the 'Vendor' for JNLP generation -->
        <name>Sicoob Credinor</name>
        <url>http://www.sicoobcredinor.com.br</url>
    </organization>

    <properties>
        ...
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
    </properties>
    
    ...
    
    <build>
        <plugins>
            <plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>2.0</version>
                <configuration>

                    <mainClass>br.com.sicoobcredinor.sascfx.SascFx</mainClass>
			...

                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
      
        <!-- JavaFX -->
        
    	<dependency>
        	<groupId>com.oracle</groupId>
        	<artifactId>javafx</artifactId>
        	<version>2.2.21</version>
        	<systemPath>${jfxrt.jar}</systemPath>
        	<scope>system</scope>
    	</dependency> 
    	
   	...
		
    </dependencies>

    ...

</project>
```

My system version:
```
Apache Maven 3.0.4 (r1232337; 2012-01-17 06:44:56-0200)
Maven home: C:\apache-maven-3.0.4
Java version: 1.7.0_25, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_25\jre
Default locale: pt_BR, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"
```

So, what's going on?

**Comment by FibreFoX** [comment]
Closed, because no bug of javafx-maven-plugin
