### ISSUE TITLE
Problems with javafx-maven-plugin and 1.7.0_40

### ISSUE THREAD

**Issue by kpenrose** [javafx-maven-plugin/javafx-maven-plugin#45]
I have been using your plugin successfully with javafx/netbeans up until the release of 1.7.0_40.  Now that I have installed that version of java, I can no longer build and run applications that worked perfectly well before.  Inside of NetBeans I get unsatisfied linker errors, and when running packaged apps built against the u25 release (executed with u40 java) I get some type of unrecoverable execution error.  I'm thinking that something in the packaging has changed, but I'm in a bind as some users in our company have started upgrading to u40, and it's breaking things.   Help, please!

Errors on "run" in NetBeans:

    [exec:exec]
    2013-09-19 08:17:19,228 [INFO  PricingMainFactory] - Starting PricingClient.
    Exception in thread "main" java.lang.RuntimeException: Application launch error
	    at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:122)
	    at java.lang.Thread.run(Thread.java:724)
    Caused by: java.lang.UnsatisfiedLinkError:     com.sun.glass.ui.win.WinApplication._invokeLater(Ljava/lang/Runnable;)V
	    at com.sun.glass.ui.win.WinApplication._invokeLater(Native Method)
	    at com.sun.glass.ui.Application.invokeLater(Application.java:343)
	    at com.sun.javafx.tk.quantum.QuantumToolkit.defer(QuantumToolkit.java:620)
	    at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:170)
	    at com.sun.javafx.application.PlatformImpl.runAndWait(PlatformImpl.java:203)
	    at com.sun.javafx.application.PlatformImpl.tkExit(PlatformImpl.java:311)
	    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:421)
	    at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:47)
	    at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:115)
	... 1 more

**Comment by FibreFoX** [comment]
Looks like a bug between javafx and maven: https://community.oracle.com/thread/2583350
Maybe related to #44
