### ISSUE TITLE
Cannot build when target/classes does not exist

### ISSUE THREAD

**Issue by rossjudson** [javafx-maven-plugin/javafx-maven-plugin#64]
When using the jfx plugin from a POM project that aggregates together others, the JarMojo fails because target/classes does not exist. The target/classes path should not be appended to the resources unless it exists.

  Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to build JFX JAR for application
	at com.zenjava.javafx.maven.plugin.JarMojo.execute(JarMojo.java:110)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 23 more
Caused by: com.sun.javafx.tools.packager.PackagerException: Error: Failed to create jar file fikon-distribution-core-1.1.0-SNAPSHOT-jfx.jar
	at com.sun.javafx.tools.packager.PackagerLib.packageAsJar(PackagerLib.java:309)
	at com.zenjava.javafx.maven.plugin.JarMojo.execute(JarMojo.java:108)
	... 25 more
Caused by: java.io.FileNotFoundException: Input folder does not exist [/home/rjudson/fio/flashcenter/src/ioncli/fikon-distribution-core/target/classes]
	at com.sun.javafx.tools.packager.PackagerLib.jar(PackagerLib.java:1476)
	at com.sun.javafx.tools.packager.PackagerLib.jar(PackagerLib.java:1389)
	at com.sun.javafx.tools.packager.PackagerLib.packageAsJar(PackagerLib.java:305)

**Comment by FibreFoX** [comment]
This should be fixed with pullrequest #108, could you retry with current master-branch? Maybe you want to integrate native-generation into maven-lifecycle (will be documented soon).
