### ISSUE TITLE
Unknown archiver type: No such archiver: 'pom'

### ISSUE THREAD

**Issue by kashammi** [javafx-maven-plugin/javafx-maven-plugin#9]
Attempting to include the eclipselink-wrapper dependency results in the following error while executing the jfx:build-jar goal of the javafx-maven-plugin:

[INFO] Unpacking /home/zzz/.m2/repository/org/glassfish/persistence/eclipselink-wrapper/3.1.1/eclipselink-wrapper-3.1.1.pom to /nfs/home/zzz/Development/projects/xxx/yyy/yyy/target/jfx-dependencies with includes "" and excludes ""
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal com.zenjava:javafx-maven-plugin:1.3:build-jar (default-cli) on project desktop: Unable to execute mojo: Unknown archiver type: No such archiver: 'pom'. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.zenjava:javafx-maven-plugin:1.3:build-jar (default-cli) on project desktop: Unable to execute mojo
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to execute mojo
    at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:95)
    at com.zenjava.javafx.maven.plugin.BuildJarMojo.unpackDependencies(BuildJarMojo.java:68)
    at com.zenjava.javafx.maven.plugin.BuildJarMojo.execute(BuildJarMojo.java:52)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
Caused by: org.apache.maven.plugin.MojoExecutionException: Unknown archiver type
    at org.apache.maven.plugin.dependency.AbstractDependencyMojo.unpack(AbstractDependencyMojo.java:270)
    at org.apache.maven.plugin.dependency.UnpackDependenciesMojo.execute(UnpackDependenciesMojo.java:91)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:93)
    ... 23 more
Caused by: org.codehaus.plexus.archiver.manager.NoSuchArchiverException: No such archiver: 'pom'.
    at org.codehaus.plexus.archiver.manager.DefaultArchiverManager.getUnArchiver(DefaultArchiverManager.java:77)
    at org.codehaus.plexus.archiver.manager.DefaultArchiverManager.getUnArchiver(DefaultArchiverManager.java:122)
    at org.apache.maven.plugin.dependency.AbstractDependencyMojo.unpack(AbstractDependencyMojo.java:233)
    ... 26 more

**Comment by Fruchuxs** [comment]
Over three years later, I got this issue.

`        <dependency>
            <groupId>org.twitter4j</groupId>
            <artifactId>twitter4j</artifactId>
            <version>4.0.5</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
`

It changes nothing, same bug. I used a Netbeans configured maven JavaFX project and after searching five hours around i'm just frustrated ..
